spring:
  datasource:
    url: ___
    username: ___
    password: ___
    driver-class-name: ___
  jpa:
    show-sql: ___
    hibernate.ddl-auto: ___

security:
  jwt:
    secret: ___
#    seconds
    expiration: 604800

logging:
  level:
    root: info
    web: error
    sql: error
  file:
      name: src/app.log
      max-history: 1
  pattern:
    file: '%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
