version: '2'

services:
  app:
    container_name: app
    image: 'voting-system-rest:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/voting-system-rest-db
      - SPRING_DATASOURCE_USERNAME=user01
      - SPRING_DATASOURCE_PASSWORD=password01
      - SECURITY_JWT_SECRET=4528482B4D6251655468566D597133743677397A24432646294A404E63526655
      - SECURITY_JWT_EXPIRATION=604800
      - PROFILING_ALL_CONTROLLERS=FALSE
  db:
    container_name: db
    image: 'postgres:14.5-alpine'
    volumes:
      - db-data-voting-system-rest:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=voting-system-rest-db
      - POSTGRES_USER=user01
      - POSTGRES_PASSWORD=password01
volumes:
  db-data-voting-system-rest:
    external: true